{
 "title": "Analysis",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Performed Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1328",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1326",
       "field": "project_ref.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Applied Miners",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "Wordcount",
     "bucketAggs": [
      {
       "$$hashKey": "object:5008",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5006", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "miners:\"wordcount\"",
     "timeField": "created_at"
    },
    {
     "alias": "Comments",
     "bucketAggs": [
      {
       "$$hashKey": "object:5026",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5024", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "miners:\"comments\"",
     "timeField": "created_at"
    },
    {
     "alias": "Declarations",
     "bucketAggs": [
      {
       "$$hashKey": "object:5147",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5145", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "miners:\"declarations\"",
     "timeField": "created_at"
    },
    {
     "alias": "Scoped Declarations",
     "bucketAggs": [
      {
       "$$hashKey": "object:5165",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5163", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "miners:\"scoped-declarations\"",
     "timeField": "created_at"
    },
    {
     "alias": "Global Frequency Table",
     "bucketAggs": [
      {
       "$$hashKey": "object:5183",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5181", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "miners:\"global-frequency-table\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Applied Splitters",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "Conserv",
     "bucketAggs": [
      {
       "$$hashKey": "object:5008",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5006", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "splitters:\"conserv\"",
     "timeField": "created_at"
    },
    {
     "alias": "Greedy",
     "bucketAggs": [
      {
       "$$hashKey": "object:5026",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5024", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "splitters:\"greedy\"",
     "timeField": "created_at"
    },
    {
     "alias": "Samurai",
     "bucketAggs": [
      {
       "$$hashKey": "object:5147",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5145", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "splitters:\"samurai\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Applied Expanders",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "alias": "NoExp",
     "bucketAggs": [
      {
       "$$hashKey": "object:5008",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5006", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "expanders:\"noexp\"",
     "timeField": "created_at"
    },
    {
     "alias": "Basic",
     "bucketAggs": [
      {
       "$$hashKey": "object:5026",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5024", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "expanders:\"basic\"",
     "timeField": "created_at"
    },
    {
     "alias": "AMAP",
     "bucketAggs": [
      {
       "$$hashKey": "object:5147",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:5145", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "expanders:\"amap\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Global overview of processed files",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of Files" }
   ],
   "targets": [
    {
     "alias": "Total Files",
     "bucketAggs": [
      {
       "$$hashKey": "object:791",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:789",
       "field": "files_summary.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    },
    {
     "alias": "Valid Files",
     "bucketAggs": [
      {
       "$$hashKey": "object:817",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:815",
       "field": "files_summary.valid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    },
    {
     "alias": "Error Files",
     "bucketAggs": [
      {
       "$$hashKey": "object:1045",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1043",
       "field": "files_summary.failed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Global overview of extracted identifiers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Identifiers",
     "bucketAggs": [
      {
       "$$hashKey": "object:1160",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1158",
       "field": "identifiers_summary.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    },
    {
     "alias": "Valid Identifiers",
     "bucketAggs": [
      {
       "$$hashKey": "object:1198",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1196",
       "field": "identifiers_summary.valid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    },
    {
     "alias": "Error identifiers",
     "bucketAggs": [
      {
       "$$hashKey": "object:1220",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1218",
       "field": "identifiers_summary.failed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "List of Analyzed Projects",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:1592",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "*",
     "timeField": "created_at"
    }
   ]
  }
 ]
}