{
 "title": "Identifiers",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Extracted Identifiers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:378",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:376", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Identifier Type Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:945",
       "fake": true,
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:933",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:931", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Package Exported Identifiers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1129",
       "fake": true,
       "field": "is_exported",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1117",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1115", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Average Extracted Identifiers per Repository",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:479",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:477",
       "field": "identifiers_summary.total",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "avg"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Identifier Type Distribution (%)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:296",
       "fake": true,
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:276",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:274", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Package Exported Identifiers (%)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1129",
       "fake": true,
       "field": "is_exported",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1117",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1115", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Identifiers Splits (by Algorithm)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:742",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Identifiers Expansions (by Algorithm)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:742",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "created_at"
    }
   ]
  }
 ]
}