global:
    scrape_interval:     10s # By default, scrape targets every 15 seconds.
    evaluation_interval: 10s # By default, scrape targets every 15 seconds.

    external_labels:
        monitor: 'src-reader'
  
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 10s
      static_configs:
           - targets: ['localhost:9090']
