@@startuml Adapter Class Diagram

package adapter {

    package algorithm {
        package expander {
            class expander.AMAP
            class expander.Basic
            class expander.Noexp
        }
        package extractor {}
        package miner {}
        package splitter {}
    }

    package frequencytable {
        class frequencytable.Global
    }

    package repository {
        package github {
            class github.MetadataRepository
            class github.SourceCodeRepository
        }

        package mongodb {
            class mongodb.MongoDBClient
            class mongodb.ProjectRepository
            class mongodb.AnalysisRepository
        }

        package memory {
            class memory.ProjectRepository
        }

        package csv {
            class csv.IdentifierRepository
        }
    }
}

@@enduml
