@@startuml Entities Layer

class Project {
    + Name string
    + Stars int
    + Contributors int
    + License string
    + YearSince int
    --
    + GetFiles()
}

Project *-- File

class File {
    + Name string
    + AST blob
    + RewrittenAST blob
}

File *-- Identifier

class Identifier {
    + Name string
    + Location string
    + Type string
    + Visibility string
}
note right of Identifier
    Visibility can be:
        - Public
        - Package
        - Local
        - Control structure
end note

Identifier *-- Split

class Split {
    + Value string
    + By string
}

Identifier *-- Expansion

class Expansion {
    + Value string
    + By string
}

note right of Expansion
    Perhaps Split and Expansion should be connected.
end note

@@enduml