@@startuml Pipeline State Diagram

state Accepted
state "In Process" as InProcess
state Finished
note right of Finished
    When issues arise during the
    splitting/expanding phases, the process
    is still considered "finished".
end note
state Failed
note right of Failed
    When issues arise while cloning,
    parsing or mining the repository,
    the process is considered "failed".
end note

[*] --> Accepted
Accepted --> InProcess
InProcess --> Failed
Failed --> [*]

InProcess --> Finished
Finished --> [*]

@@enduml