@@startuml Pipeline Class Diagram

interface Splitter {
    Name()
    Split(string) []string
}

Splitter <|--- Conserv
Splitter <|--- Greedy
Splitter <|--- Samurai

class Conserv
Conserv --> token.conserv.Exported

class Greedy
class Samurai

interface Expander {
    name()
    Expand([]string) []string
}

Expander <|--- Basic
Expander <|--- AMAP
Expander <|--- Normalize

class Basic
class AMAP
class Normalize

package token.conserv {
    class Exported <<package>> {
        Split(string) []string
    }
}

@@enduml