@@startuml system_activity_diagram

start
:Clone the repository;
:Parse the files and obtain ASTs;
:Merge files into one stream;

fork
    :Mine by Count;
fork again
    :Mine by Scope;
fork again
    :Mine by Declaration;
end fork

:Extract the identifiers;

fork
    :Create Conserv;
    :Split by Conserv;
fork again
    :Create Greedy;
    :Split by Greedy;
fork again
    :Create Samurai;
    :Split By Samurai;
fork again
    :Split/Expand by GenTest;
    note right
        Not included on the
        current version.
    end note
end fork

fork
    :Rewrite AST;
fork again
    :Extract Metrics;
end fork

:Store Results;

end

@@enduml