@@startuml System Use Cases

actor User

rectangle "src-reader" {
    usecase (Create Project) as CreateProject
    usecase (Analyze Project) as AnalyzeProject
    usecase (Extract Insights \nfrom analysis) as ExtractInsights
    usecase (Retrieve original File) as RetrieveOriginalFile
    usecase (Retrieve rewritten File) as RetrieveRewrittenFile
}

left to right direction

User --> CreateProject
User --> AnalyzeProject
User --> ExtractInsights
User --> RetrieveOriginalFile
User --> RetrieveRewrittenFile

@@enduml
