{
 "title": "Insights",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "url",
    "label": "Repository",
    "query": "{\n\t\"query\": {\n\t    \"match_all\": {}\n\t},\n\t\"_source\": {\n\t    \"includes\": [\"url\"]\n\t}\n}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Repository Accuracy",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:179",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:177",
       "field": "accuracy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Repository Overview",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:205",
       "fake": true,
       "field": "package.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:193",
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:191",
       "field": "accuracy",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accuracy by Package",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:204",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:974",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "created_at"
    }
   ]
  }
 ]
}