{
 "title": "Projects",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Imported Projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:741",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:739",
       "field": "metadata.fullname.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "Distribution of creation dates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:93",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "1M", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:91", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "Distribution of Licenses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1469",
       "fake": true,
       "field": "metadata.license.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1443",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1441",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "Average Files per Repository",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:7886",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7884",
       "field": "source_code.files_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "Average Repository Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1809",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1807",
       "field": "metadata.size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "Average Repository Stargazers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1865",
       "field": "metadata.created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1863",
       "field": "metadata.stargazers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "List of Projects/Repositories",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:2034",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  },
  {
   "title": "List of Files per Repository",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:5155",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "metadata.created_at"
    }
   ]
  }
 ]
}